<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>default</LangVersion>
    </PropertyGroup>
    <ItemGroup>
      <Compile Update="InputManagers\KeyboardManager.cs">
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>
</Project>
